spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tenselite?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC
    username: root
    password: rootpassword
    hikari:
      initialization-fail-timeout: 0
      data-source-properties:
        cacheDefaultTimezone: false

  # https://flywaydb.org/documentation/callbacks.html
  flyway:
    locations: classpath:/db/migration

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

jwt:
  defaultPassword: pass
  secret: secret
  expirationInMs: 86400000 # 1 day
